# 所有基础环境服务的配置文件

networks:
  juzipi_network:
    driver: bridge

services:
  mysql:
    image: mysql
    restart: "no" # 重启策略
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=juzipi
    ports:
      - 3306:3306
    networks:
      - juzipi_network
    healthcheck: # 健康检查
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p12345678" ]
      timeout: 5s
      interval: 10s # 每10秒检查一次
      retries: 3 # 尝试3次

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - juzipi_network
    healthcheck: # 健康检查
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 5s
      interval: 10s # 每10秒检查一次
      retries: 3 # 尝试3次
